
INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`,`rules`,`field_mappings`)
SELECT * FROM ( SELECT 'Actor','com_eventschedule.actor','{"special":{"dbtable":"#__eventschedule_actors","key":"id","type":"Actor","prefix":"EventscheduleTable"}}', '{"formFile":"administrator\/components\/com_eventschedule\/models\/forms\/actor.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"schedule","targetTable":"#__eventschedule_eventschedules","targetColumn":"id","displayColumn":"title"}]}', CASE WHEN 'rules' is null THEN " " ELSE " " END as rules, CASE  WHEN 'field_mappings' is null THEN " " ELSE " " END as field_mappings) AS tmp
WHERE NOT EXISTS (
	SELECT type_alias FROM `#__content_types` WHERE (`type_alias` = 'com_eventschedule.actor')
) LIMIT 1;

UPDATE `#__content_types` SET
	`type_title` = 'Actor', 
	`table` = '{"special":{"dbtable":"#__eventschedule_actors","key":"id","type":"Actor","prefix":"EventscheduleTable"}}', 
	`content_history_options` = '{"formFile":"administrator\/components\/com_eventschedule\/models\/forms\/actor.xml", "hideFields":["checked_out","checked_out_time","params","language"], "ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time"], "convertToInt":["publish_up", "publish_down"], "displayLookup":[{"sourceColumn":"catid","targetTable":"#__categories","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"group_id","targetTable":"#__usergroups","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"created_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"access","targetTable":"#__viewlevels","targetColumn":"id","displayColumn":"title"},{"sourceColumn":"modified_by","targetTable":"#__users","targetColumn":"id","displayColumn":"name"},{"sourceColumn":"schedule","targetTable":"#__eventschedule_eventschedules","targetColumn":"id","displayColumn":"title"}]}'
WHERE (`type_alias` = 'com_eventschedule.actor');
